# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finetune_serve_http.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x66inetune_serve_http.proto\x12\x18\x65ndpoints.finetune.serve\x1a\x1cgoogle/api/annotations.proto\"t\n\rPromptRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x18\n\x10token_max_length\x18\x02 \x01(\x03\x12\x13\n\x0btemperature\x18\x03 \x01(\x01\x12\r\n\x05top_p\x18\x04 \x01(\x01\x12\x15\n\rstop_sequence\x18\x05 \x01(\t\"\xac\x01\n\x0ePromptResponse\x12\r\n\x05model\x18\x01 \x01(\t\x12\x14\n\x0c\x63ompute_time\x18\x02 \x01(\x01\x12\x10\n\x08response\x18\x03 \x01(\t\x12\x0e\n\x06prompt\x18\x04 \x01(\t\x12\x18\n\x10token_max_length\x18\x05 \x01(\x03\x12\x13\n\x0btemperature\x18\x06 \x01(\x01\x12\r\n\x05top_p\x18\x07 \x01(\x01\x12\x15\n\rstop_sequence\x18\x08 \x01(\t2\x80\x01\n\rFinetuneServe\x12o\n\x06Prompt\x12\'.endpoints.finetune.serve.PromptRequest\x1a(.endpoints.finetune.serve.PromptResponse\"\x12\x82\xd3\xe4\x93\x02\x0c\x12\n/v1/promptB;\n#com.google.endpoints.finetune.serveB\x12\x46inetuneServeProtoP\x01\x62\x06proto3')



_PROMPTREQUEST = DESCRIPTOR.message_types_by_name['PromptRequest']
_PROMPTRESPONSE = DESCRIPTOR.message_types_by_name['PromptResponse']
PromptRequest = _reflection.GeneratedProtocolMessageType('PromptRequest', (_message.Message,), {
  'DESCRIPTOR' : _PROMPTREQUEST,
  '__module__' : 'finetune_serve_http_pb2'
  # @@protoc_insertion_point(class_scope:endpoints.finetune.serve.PromptRequest)
  })
_sym_db.RegisterMessage(PromptRequest)

PromptResponse = _reflection.GeneratedProtocolMessageType('PromptResponse', (_message.Message,), {
  'DESCRIPTOR' : _PROMPTRESPONSE,
  '__module__' : 'finetune_serve_http_pb2'
  # @@protoc_insertion_point(class_scope:endpoints.finetune.serve.PromptResponse)
  })
_sym_db.RegisterMessage(PromptResponse)

_FINETUNESERVE = DESCRIPTOR.services_by_name['FinetuneServe']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n#com.google.endpoints.finetune.serveB\022FinetuneServeProtoP\001'
  _FINETUNESERVE.methods_by_name['Prompt']._options = None
  _FINETUNESERVE.methods_by_name['Prompt']._serialized_options = b'\202\323\344\223\002\014\022\n/v1/prompt'
  _PROMPTREQUEST._serialized_start=85
  _PROMPTREQUEST._serialized_end=201
  _PROMPTRESPONSE._serialized_start=204
  _PROMPTRESPONSE._serialized_end=376
  _FINETUNESERVE._serialized_start=379
  _FINETUNESERVE._serialized_end=507
# @@protoc_insertion_point(module_scope)
