# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finetune_serve.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66inetune_serve.proto\x12\x18\x65ndpoints.finetune.serve\"t\n\rPromptRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x18\n\x10token_max_length\x18\x02 \x01(\x03\x12\x13\n\x0btemperature\x18\x03 \x01(\x01\x12\r\n\x05top_p\x18\x04 \x01(\x01\x12\x15\n\rstop_sequence\x18\x05 \x01(\t\"\xac\x01\n\x0ePromptResponse\x12\r\n\x05model\x18\x01 \x01(\t\x12\x14\n\x0c\x63ompute_time\x18\x02 \x01(\x01\x12\x10\n\x08response\x18\x03 \x01(\t\x12\x0e\n\x06prompt\x18\x04 \x01(\t\x12\x18\n\x10token_max_length\x18\x05 \x01(\x03\x12\x13\n\x0btemperature\x18\x06 \x01(\x01\x12\r\n\x05top_p\x18\x07 \x01(\x01\x12\x15\n\rstop_sequence\x18\x08 \x01(\x01\x32n\n\rFinetuneServe\x12]\n\x06Prompt\x12\'.endpoints.finetune.serve.PromptRequest\x1a(.endpoints.finetune.serve.PromptResponse\"\x00\x42;\n#com.google.endpoints.finetune.serveB\x12\x46inetuneServeProtoP\x01\x62\x06proto3')



_PROMPTREQUEST = DESCRIPTOR.message_types_by_name['PromptRequest']
_PROMPTRESPONSE = DESCRIPTOR.message_types_by_name['PromptResponse']
PromptRequest = _reflection.GeneratedProtocolMessageType('PromptRequest', (_message.Message,), {
  'DESCRIPTOR' : _PROMPTREQUEST,
  '__module__' : 'finetune_serve_pb2'
  # @@protoc_insertion_point(class_scope:endpoints.finetune.serve.PromptRequest)
  })
_sym_db.RegisterMessage(PromptRequest)

PromptResponse = _reflection.GeneratedProtocolMessageType('PromptResponse', (_message.Message,), {
  'DESCRIPTOR' : _PROMPTRESPONSE,
  '__module__' : 'finetune_serve_pb2'
  # @@protoc_insertion_point(class_scope:endpoints.finetune.serve.PromptResponse)
  })
_sym_db.RegisterMessage(PromptResponse)

_FINETUNESERVE = DESCRIPTOR.services_by_name['FinetuneServe']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n#com.google.endpoints.finetune.serveB\022FinetuneServeProtoP\001'
  _PROMPTREQUEST._serialized_start=50
  _PROMPTREQUEST._serialized_end=166
  _PROMPTRESPONSE._serialized_start=169
  _PROMPTRESPONSE._serialized_end=341
  _FINETUNESERVE._serialized_start=343
  _FINETUNESERVE._serialized_end=453
# @@protoc_insertion_point(module_scope)
